name: Run
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout spark-scala3
        uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Run tests
        run: sbt "encoders / test"
      - name: Run WordCount
        timeout-minutes: 5
        run: sbt "examples / runMain rdd.wordcount"
      - name: Run Dataset-based WordCount
        timeout-minutes: 5
        run: sbt "examples / runMain rdd.wordcountSql"


