name: Run
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Show dependencies
        run: sbt "encoders / dependencyTree"
      - name: Run WordCount
        timeout-minutes: 5
        run: sbt "examples / runMain rdd.wordcount"
      - name: Run EncoderYours
        timeout-minutes: 5
        run: sbt "examples / runMain sql.encoderMine"

